### ISSUE TITLE
add a method in rust lib for getting a constant phantom hash field element

### ISSUE THREAD

**Issue by alsala** [HorizenOfficial/zend_oo#100]
Introduce a utility method, to be used for instance from zendoo_mc_cryptolib, to retrieve a constant phantom hash field element.

**Comment by ptagl** [comment]
This function is not needed anymore since the phantom hash (for `ActiveCertDataHash`) is computed internally to the `McCryptoLib`; another usage of this hash is internal to _Zendoo_ (for the computation of the `defaultScCumTreeHash` to be used for the first sidechain block), but we can handle this case with a field element deserialized from a vector filled with '0' values.
